import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
declare const google: any;

interface Marker {
    lat: number;
    lng: number;
    label?: string;
    draggable?: boolean;
}
const data = {
    chart: {
        caption: "Power generated by Wind Farm",
        captionontop: "120 MegaWatt",
        origw: "380",
        origh: "250",
        gaugestartangle: "135",
        gaugeendangle: "45",
        gaugeoriginx: "190",
        gaugeoriginy: "220",
        gaugeouterradius: "190",
        theme: "candy",
        showvalue: "1",
        numbersuffix: " %",
        valuefontsize: "25"
    },
    colorrange: {
        color: [
            {
                minvalue: "0",
                maxvalue: "25",
                code: "	#ADD8E6"
            },
            {
                minvalue: "25",
                maxvalue: "50",
                code: "#62B58F "
            },
            {
                minvalue: "50",
                maxvalue: "75",
                code: "#FFC533 "
            }
            , {
                minvalue: "75",
                maxvalue: "100",
                code: "#F2726F"
            }
        ]
    },
    dials: {
        dial: [
            {
                value: "0.3",
                tooltext: "Moderate Pressure"
            }
        ]
    }
};
@Component({
    selector: 'app-windPlant',
    templateUrl: './windPowerPlant.component.html',
    styleUrls: ['./windPowerPlant.component.css']
})
export class WindPowerPlantComponent implements OnInit {

    windPowerPlant
    width = 450;
    height = 400;
    type = "angulargauge";
    dataFormat = "json";
    dataSource = data;
    urlID;
    constructor(private route: ActivatedRoute) {
        this.route.params.subscribe(params => {

            console.log(params['id']);
            this.urlID = params['id'];
        })
    }


    ngOnInit() {


        this.windPowerPlant = [
            {
                id: 0,
                lat: 13.917479,
                lng: 76.066269,
                name: 'Acciona Tuppadahalli',
                location: 'Chitradurga, Karnataka',
                capacity: "56.1 MegaWatt",
                image_src: 'Acciona',
            },
            {
                id: 1,
                lng: 15.736414,
                lat: 75.970502,
                name: 'Shah Gajendragarh MMTCL',
                location: ' Gadag, Karnataka',
                capacity: " 15 MegaWatt ",
                image_src: 'MMTCL',
            },
            {
                id: 2,
                lng: 14.172776,
                lat: 76.390727,
                name: 'Jogmatti BSES',
                location: 'Chitradurga, Karnataka ',
                capacity: " 14 MegaWatt",
                image_src: 'Jogmatti',
            },
            {
                id: 3,
                lng: 15.736538,
                lat: 75.971575,
                name: 'Shah Gajendragarh',
                location: 'Gadag, Karnataka',
                capacity: "10.8 MegaWatt",
                image_src: 'Gajendragarh',
            },
        ];

    

        this.googleMapIntialization();
    }

    googleMapIntialization() {
        this.lat = this.windPowerPlant[this.urlID].lat;
        this.lng = this.windPowerPlant[this.urlID].lng;

        // lat = 14.138323;
        // lng = 77.314646;

        this.coordinates = new google.maps.LatLng(this.lat, this.lng);



        const mapOptions: google.maps.MapOptions = {
            center: this.coordinates,
            zoom: 17,
            mapTypeId: google.maps.MapTypeId.HYBRID
        };

        this.marker = new google.maps.Marker({
            position: this.coordinates,
            map: this.map,
            title: this.getCustomTitle()
        });

        this.MymapOptions = mapOptions

    }

    title = 'angular-gmap';
    @ViewChild('mapContainer', { static: false }) gmap: ElementRef;
    map: google.maps.Map;
    lat;
    lng;
    coordinates;
    marker;
    MymapOptions

    ngAfterViewInit() {
        this.mapInitializer();
    }

    mapInitializer() {
        this.map = new google.maps.Map(this.gmap.nativeElement,
            this.MymapOptions);
        this.marker.setMap(this.map);
    }

    getCustomTitle() {
        return 'Power Plant : ' + this.windPowerPlant[this.urlID].name + "\n Maximum Power Generation :240MegaWatt " +
            "\nCurrent power generation :120 MegaWatt\n\n" + 'Status: No Issue';
    }


}
